const SET_CURRENT_TAG = 'SET_CURRENT_TAG';
const SHOW_MODAL = 'SHOW_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const NEW_TAG = 'NEW_TAG';
const DELETE_TAG = 'DELETE_TAG';

export {
  SET_CURRENT_TAG, SHOW_MODAL, CLOSE_MODAL, NEW_TAG, DELETE_TAG
};
